/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiringRouteImport } from './routes/airing'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeasonalRouteImport } from './routes/seasonal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthedLibraryRouteImport } from './routes/_authed/library'
import { Route as AnimeIdRouteImport } from './routes/anime/$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as CharacterIdRouteImport } from './routes/character/$id'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiringRoute = AiringRouteImport.update({
  id: '/airing',
  path: '/airing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalRoute = SeasonalRouteImport.update({
  id: '/seasonal',
  path: '/seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLibraryRoute = AuthedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthedRoute,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airing': typeof AiringRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image': typeof OgImageRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library': typeof AuthedLibraryRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/$': typeof ApiSplatRoute
  '/character/$id': typeof CharacterIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/u/$handle': typeof UHandleRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airing': typeof AiringRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image': typeof OgImageRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library': typeof AuthedLibraryRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/$': typeof ApiSplatRoute
  '/character/$id': typeof CharacterIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/u/$handle': typeof UHandleRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/airing': typeof AiringRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og-image': typeof OgImageRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authed/library': typeof AuthedLibraryRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/$': typeof ApiSplatRoute
  '/character/$id': typeof CharacterIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/u/$handle': typeof UHandleRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airing'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og-image'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/seasonal'
    | '/sitemap.xml'
    | '/library'
    | '/anime/$id'
    | '/api/$'
    | '/character/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/u/$handle'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airing'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og-image'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/seasonal'
    | '/sitemap.xml'
    | '/library'
    | '/anime/$id'
    | '/api/$'
    | '/character/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/u/$handle'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/airing'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og-image'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/seasonal'
    | '/sitemap.xml'
    | '/_authed/library'
    | '/anime/$id'
    | '/api/$'
    | '/character/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/u/$handle'
    | '/_authed/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiringRoute: typeof AiringRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgImageRoute: typeof OgImageRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SeasonalRoute: typeof SeasonalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnimeIdRoute: typeof AnimeIdRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CharacterIdRoute: typeof CharacterIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airing': {
      id: '/airing'
      path: '/airing'
      fullPath: '/airing'
      preLoaderRoute: typeof AiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal': {
      id: '/seasonal'
      path: '/seasonal'
      fullPath: '/seasonal'
      preLoaderRoute: typeof SeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/library': {
      id: '/_authed/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthedLibraryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedLibraryRoute: typeof AuthedLibraryRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLibraryRoute: AuthedLibraryRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  AiringRoute: AiringRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgImageRoute: OgImageRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SeasonalRoute: SeasonalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnimeIdRoute: AnimeIdRoute,
  ApiSplatRoute: ApiSplatRoute,
  CharacterIdRoute: CharacterIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
